base_config:
  message: "NULL"
  spec_app_list: null
  spec_apps: "cactusADM,tonto"
  elf_folder: "./jemalloc_elf"
  times: "1,1,1"
  start_id: "0,0,0"
  emulator: "QEMU"
  build_bbl_only: true
  max_threads: 70
  CPU2017: false
  generate_rootfs_script_only: false
  copies: 2
  archive_id: null
  redirect_output: false
  cpu_bind: 0
  mem_bind: 0
  bootloader: "opensbi"
  all_in_one_workload: true
  boot_for_test: true
archive_id_config:
  gcc_version: "gcc12.2.0"
  riscv_ext: "rv64gcb"
  base_or_fixed: "base"
  special_flag: "intFppOff_for_qemu_dual_core"
  group: "archgroup"